// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css"; // kalau kamu punya CSS global
import Footer from "./components/Footer";
import Header from "./components/Header";
import ClientLayout from "./ClientLayout";
import { Provider } from 'react-redux';
import { store } from '@/store';
import { Providers } from '@/store/providers';
import AuthProvider from "@/store/AuthProvider";

const geistSans = Geist({
variable: "--font-geist-sans",
subsets: ["latin"],
});

const geistMono = Geist_Mono({
variable: "--font-geist-mono",
subsets: ["latin"],
});

export const metadata: Metadata = {
title: "Create Next App",
description: "Generated by create next app",
};

export default function RootLayout({
children,
}: Readonly<{ children: React.ReactNode }>) {
return (
	<html lang="en">
	<head>
		{/* Bootstrap */}
		<link
		href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
		rel="stylesheet"
		integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
		crossOrigin="anonymous"
		/>

		{/* Font Awesome */}
		<link
		href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
		rel="stylesheet"
		/>

		{/* CSS local dari public/css */}
		<link href="/assets/css/bootstrap.min.css" rel="stylesheet" />
		<link href="/assets/css/tiny-slider.css" rel="stylesheet" />
		<link href="/assets/css/style.css" rel="stylesheet" />
	</head>
	<body className={`${geistSans.variable} ${geistMono.variable}`}>
		<Providers>
			<AuthProvider>
				<ClientLayout>
					{children}
				</ClientLayout>
			</AuthProvider>
		</Providers>

		{/* JS Bootstrap bundle */}
		<Script src="/assets/js/bootstrap.bundle.min.js" strategy="beforeInteractive" />
		{/* tiny-slider */}
		<Script src="/assets/js/tiny-slider.js" strategy="afterInteractive" />
		{/* custom.js */}
		<Script src="/assets/js/custom.js" strategy="afterInteractive" />
	</body>
	</html>
);
}
